require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

RSpec/ExampleLength:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleSubjects:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Lint/MissingSuper:
  Enabled: false