version: "3.9"
services:
  db:
    image: postgres:15.0
    restart: always
    container_name: translator-api-database
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "db"
    ports:
      - "5432:5432"
    env_file: .env
  app:
    image: translator_api
    restart: always
    container_name: translator-api
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "db"
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file: .env

volumes:
  pg-data:
    driver: local